### ISSUE TITLE
LIN TX on Channel 1 not working?

### ISSUE THREAD

**Issue by rocketjosh** [macchina/m2-libraries#3]
It appears as though `LIN1.write(` may not be working? `LIN2.write(` **does** appear to work. Tested using this [example](https://github.com/macchina/m2-libraries/blob/master/LIN/examples/Master/Master.ino).

RX on both channels does work as verified using this [example](https://github.com/macchina/m2-libraries/blob/master/LIN/examples/Sniffer/Sniffer.ino).

**Comment by adamvoss** [comment]
This issue was moved to macchina/LIN#5
